changelog:
  categories:
    - title: "🚀 Features"
      labels:
        - enhancement
    - title: "🐛 Bug Fixes"
      labels:
        - bug
    - title: "🏗️ Build & CI"
      labels:
        - build
        - ci
    - title: "🧪 Tests"
      labels:
        - test
    - title: "📖 Documentation"
      labels:
        - documentation
    - title: "🔧 Other Changes"
      labels:
        - "*"
